// healthCorpus.js
// Closed, curated corpus of health education content sourced from WHO guidelines,
// India's National Health Mission (NHM) publications, and ASHA worker training
// materials. Every entry has:
// - id: stable reference
// - source: the actual document it came from (for citation)
// - category / tags: for search and navigation
// - content in en/hi/kn: pre-translated, not machine-generated
//
// DESIGN RULE: Nothing in this corpus was generated by an LLM. Every entry is a
// simplified restatement of content from the cited source. If you can't cite it,
// it doesn't go in.

export const CATEGORIES = [
  { id: "maternal", label: { en: "Pregnancy & maternal health", hi: "गर्भावस्था और मातृ स्वास्थ्य", kn: "ಗರ್ಭಧಾರಣೆ ಮತ್ತು ತಾಯಿ ಆರೋಗ್ಯ" }, icon: "🤰" },
  { id: "menstrual", label: { en: "Periods & menstrual health", hi: "मासिक धर्म स्वास्थ्य", kn: "ಮುಟ್ಟು ಮತ್ತು ಋತುಚಕ್ರ ಆರೋಗ್ಯ" }, icon: "🩸" },
  { id: "anaemia", label: { en: "Anaemia & nutrition", hi: "एनीमिया और पोषण", kn: "ರಕ್ತಹೀನತೆ ಮತ್ತು ಪೋಷಣೆ" }, icon: "🥗" },
  { id: "adolescent", label: { en: "Adolescent health", hi: "किशोर स्वास्थ्य", kn: "ಹದಿಹರೆಯದ ಆರೋಗ್ಯ" }, icon: "🌱" },
  { id: "infection", label: { en: "Infections & fever", hi: "संक्रमण और बुखार", kn: "ಸೋಂಕು ಮತ್ತು ಜ್ವರ" }, icon: "🤒" },
  { id: "emergency", label: { en: "When to go to hospital immediately", hi: "तुरंत अस्पताल कब जाएं", kn: "ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಯಾವಾಗ ಹೋಗಬೇಕು" }, icon: "🚨" },
  { id: "hygiene", label: { en: "Hygiene & prevention", hi: "स्वच्छता और रोकथाम", kn: "ನೈರ್ಮಲ್ಯ ಮತ್ತು ತಡೆಗಟ್ಟುವಿಕೆ" }, icon: "🧼" },
  { id: "mental", label: { en: "Mental wellbeing", hi: "मानसिक स्वास्थ्य", kn: "ಮಾನಸಿಕ ಆರೋಗ್ಯ" }, icon: "💚" },
];

export const CORPUS = [
  // ═══════════════ MATERNAL ═══════════════
  {
    id: "mat-danger-signs",
    category: "maternal",
    tags: ["pregnancy", "danger", "bleeding", "headache", "convulsions", "emergency"],
    source: "WHO Recommendations on Maternal and Newborn Care (2023); NHM Mother and Child Tracking System Guidelines",
    title: { en: "Danger signs during pregnancy", hi: "गर्भावस्था में खतरे के संकेत", kn: "ಗರ್ಭಧಾರಣೆಯಲ್ಲಿ ಅಪಾಯದ ಸೂಚನೆಗಳು" },
    content: {
      en: "Go to the nearest health facility immediately if you notice any of these during pregnancy: heavy vaginal bleeding (soaking a pad or cloth in under an hour), severe headache that does not go away with rest, blurred or disturbed vision, convulsions or fits, sudden swelling of the face or hands, severe abdominal pain, baby's movements reduced or stopped, water breaking before expected delivery date, high fever. These are warning signs recognised by the WHO as needing immediate medical attention. Do not wait to see if they improve on their own.",
      hi: "गर्भावस्था के दौरान इनमें से कोई भी लक्षण दिखे तो तुरंत नज़दीकी स्वास्थ्य केंद्र जाएं: भारी योनि रक्तस्राव (एक घंटे में पैड या कपड़ा भीग जाना), तेज़ सिरदर्द जो आराम से ठीक न हो, धुंधला दिखना, दौरे या ऐंठन, चेहरे या हाथों में अचानक सूजन, पेट में तेज़ दर्द, बच्चे की हलचल कम या बंद होना, अपेक्षित तारीख से पहले पानी की थैली फटना, तेज़ बुखार। ये चेतावनी संकेत हैं जिन्हें WHO तुरंत चिकित्सा ध्यान देने योग्य मानता है। इंतज़ार न करें।",
      kn: "ಗರ್ಭಧಾರಣೆಯಲ್ಲಿ ಈ ಯಾವುದಾದರೂ ಲಕ್ಷಣ ಕಂಡುಬಂದರೆ ತಕ್ಷಣ ಹತ್ತಿರದ ಆರೋಗ್ಯ ಕೇಂದ್ರಕ್ಕೆ ಹೋಗಿ: ಭಾರೀ ಯೋನಿ ರಕ್ತಸ್ರಾವ (ಒಂದು ಗಂಟೆಯಲ್ಲಿ ಪ್ಯಾಡ್ ಅಥವಾ ಬಟ್ಟೆ ತೊಯ್ಯುವುದು), ವಿಶ್ರಾಂತಿಯಿಂದ ಕಡಿಮೆಯಾಗದ ತೀವ್ರ ತಲೆನೋವು, ಮಸುಕಾದ ದೃಷ್ಟಿ, ಸೆಳೆತ, ಮುಖ ಅಥವಾ ಕೈಗಳಲ್ಲಿ ಇದ್ದಕ್ಕಿದ್ದಂತೆ ಊತ, ತೀವ್ರ ಹೊಟ್ಟೆ ನೋವು, ಮಗುವಿನ ಚಲನೆ ಕಡಿಮೆಯಾಗುವುದು ಅಥವಾ ನಿಲ್ಲುವುದು, ನಿರೀಕ್ಷಿತ ದಿನಾಂಕಕ್ಕಿಂತ ಮೊದಲು ನೀರು ಒಡೆಯುವುದು, ತೀವ್ರ ಜ್ವರ. ಇವು WHO ಗುರುತಿಸಿದ ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಗಮನ ಬೇಕಾದ ಎಚ್ಚರಿಕೆ ಸೂಚನೆಗಳು. ಅವು ತಾವಾಗಿ ಸುಧಾರಿಸುತ್ತವೆ ಎಂದು ಕಾಯಬೇಡಿ."
    },
  },
  {
    id: "mat-anc-visits",
    category: "maternal",
    tags: ["pregnancy", "antenatal", "checkup", "ANC"],
    source: "WHO Antenatal Care Recommendations (2016, updated 2023); NHM Janani Suraksha Yojana Guidelines",
    title: { en: "Antenatal check-ups: when and why", hi: "प्रसवपूर्व जांच: कब और क्यों", kn: "ಗರ್ಭಪೂರ್ವ ತಪಾಸಣೆ: ಯಾವಾಗ ಮತ್ತು ಏಕೆ" },
    content: {
      en: "The WHO recommends at least 8 antenatal check-ups during pregnancy. The first visit should be within the first 12 weeks. During these visits, your health worker will check your blood pressure, test for anaemia, check the baby's growth, and screen for infections. Under India's Janani Suraksha Yojana, you may be entitled to financial assistance for institutional delivery — ask your ASHA worker about this. Regular check-ups help catch problems early, before they become emergencies.",
      hi: "WHO गर्भावस्था के दौरान कम से कम 8 प्रसवपूर्व जांच की सिफारिश करता है। पहली जांच 12 सप्ताह के भीतर होनी चाहिए। इन जांचों में स्वास्थ्य कर्मी आपका रक्तचाप जांचेंगे, एनीमिया की जांच करेंगे, बच्चे की वृद्धि देखेंगे और संक्रमण की जांच करेंगे। भारत की जननी सुरक्षा योजना के तहत आपको संस्थागत प्रसव के लिए आर्थिक सहायता मिल सकती है — अपनी आशा कार्यकर्ता से पूछें। नियमित जांच से समस्याओं को आपातकालीन स्थिति बनने से पहले पकड़ा जा सकता है।",
      kn: "ಗರ್ಭಧಾರಣೆಯ ಸಮಯದಲ್ಲಿ ಕನಿಷ್ಠ 8 ಗರ್ಭಪೂರ್ವ ತಪಾಸಣೆಗಳನ್ನು WHO ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ. ಮೊದಲ ಭೇಟಿ 12 ವಾರಗಳ ಒಳಗೆ ಆಗಬೇಕು. ಈ ಭೇಟಿಗಳಲ್ಲಿ ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರು ನಿಮ್ಮ ರಕ್ತದೊತ್ತಡ ಪರೀಕ್ಷಿಸುತ್ತಾರೆ, ರಕ್ತಹೀನತೆ ಪರೀಕ್ಷಿಸುತ್ತಾರೆ, ಮಗುವಿನ ಬೆಳವಣಿಗೆ ನೋಡುತ್ತಾರೆ ಮತ್ತು ಸೋಂಕಿಗೆ ತಪಾಸಣೆ ಮಾಡುತ್ತಾರೆ. ಭಾರತದ ಜನನಿ ಸುರಕ್ಷಾ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಸಾಂಸ್ಥಿಕ ಹೆರಿಗೆಗೆ ಆರ್ಥಿಕ ಸಹಾಯ ಸಿಗಬಹುದು — ನಿಮ್ಮ ಆಶಾ ಕಾರ್ಯಕರ್ತರನ್ನು ಕೇಳಿ."
    },
  },
  {
    id: "mat-pph",
    category: "maternal",
    tags: ["postpartum", "bleeding", "haemorrhage", "delivery", "emergency"],
    source: "WHO Recommendations for the Prevention and Treatment of Postpartum Haemorrhage (2012, updated 2023)",
    title: { en: "Heavy bleeding after delivery (postpartum haemorrhage)", hi: "प्रसव के बाद भारी रक्तस्राव", kn: "ಹೆರಿಗೆಯ ನಂತರ ಭಾರೀ ರಕ್ತಸ್ರಾವ" },
    content: {
      en: "Some bleeding after delivery is normal, but heavy bleeding that soaks through a pad in less than an hour, or continues steadily, is a medical emergency called postpartum haemorrhage (PPH). PPH is the single largest cause of maternal death worldwide. What to do immediately: call for emergency help (108), keep the mother lying down with legs elevated, massage the lower abdomen firmly, and get to a facility with blood transfusion capability. The WHO recommends uterotonics (medicines given by a health worker) within the first minute after birth to prevent PPH. This is why delivering at a health facility matters.",
      hi: "प्रसव के बाद कुछ रक्तस्राव सामान्य है, लेकिन एक घंटे में पैड भीग जाना या लगातार खून बहना एक चिकित्सीय आपातकाल है — इसे प्रसवोत्तर रक्तस्राव (PPH) कहते हैं। PPH दुनिया भर में मातृ मृत्यु का सबसे बड़ा कारण है। तुरंत करें: 108 पर कॉल करें, माँ को लिटाकर पैर ऊपर रखें, पेट के निचले हिस्से पर मजबूती से मालिश करें, रक्त चढ़ाने की सुविधा वाले अस्पताल ले जाएं। WHO जन्म के बाद पहले मिनट में यूटेरोटोनिक दवा की सिफारिश करता है — इसीलिए स्वास्थ्य केंद्र में प्रसव ज़रूरी है।",
      kn: "ಹೆರಿಗೆಯ ನಂತರ ಸ್ವಲ್ಪ ರಕ್ತಸ್ರಾವ ಸಾಮಾನ್ಯ, ಆದರೆ ಒಂದು ಗಂಟೆಯಲ್ಲಿ ಪ್ಯಾಡ್ ತೊಯ್ಯುವಷ್ಟು ಅಥವಾ ನಿರಂತರವಾಗಿ ಹರಿಯುವ ಭಾರೀ ರಕ್ತಸ್ರಾವ ವೈದ್ಯಕೀಯ ತುರ್ತುಸ್ಥಿತಿ — ಇದನ್ನು ಪ್ರಸವೋತ್ತರ ರಕ್ತಸ್ರಾವ (PPH) ಎಂದು ಕರೆಯುತ್ತಾರೆ. PPH ವಿಶ್ವಾದ್ಯಂತ ತಾಯಿ ಮರಣದ ಅತಿದೊಡ್ಡ ಕಾರಣ. ತಕ್ಷಣ ಮಾಡಿ: 108 ಗೆ ಕರೆ ಮಾಡಿ, ತಾಯಿಯನ್ನು ಮಲಗಿಸಿ ಕಾಲುಗಳನ್ನು ಮೇಲೆತ್ತಿ, ಹೊಟ್ಟೆಯ ಕೆಳಭಾಗವನ್ನು ಗಟ್ಟಿಯಾಗಿ ಮಸಾಜ್ ಮಾಡಿ, ರಕ್ತ ವರ್ಗಾವಣೆ ಸೌಲಭ್ಯ ಇರುವ ಆಸ್ಪತ್ರೆಗೆ ಕರೆದೊಯ್ಯಿರಿ."
    },
  },
  {
    id: "mat-nutrition",
    category: "maternal",
    tags: ["pregnancy", "nutrition", "diet", "iron", "folic"],
    source: "WHO Guideline on Nutritional Interventions during Pregnancy (2020); NHM IFA Supplementation Programme",
    title: { en: "Nutrition during pregnancy", hi: "गर्भावस्था में पोषण", kn: "ಗರ್ಭಧಾರಣೆಯಲ್ಲಿ ಪೋಷಣೆ" },
    content: {
      en: "During pregnancy, you need more iron, folic acid, calcium, and protein than usual. The WHO and India's NHM recommend daily iron-folic acid (IFA) tablets throughout pregnancy and for 6 months after delivery. Eat dark green leafy vegetables, lentils/dal, jaggery, eggs, and millets when available. Drink plenty of water. Avoid raw or undercooked meat. If you feel very tired, dizzy, or your nails and inner eyelids look pale, tell your health worker — these can be signs of anaemia, which is common and treatable but dangerous if ignored during pregnancy.",
      hi: "गर्भावस्था में सामान्य से अधिक आयरन, फॉलिक एसिड, कैल्शियम और प्रोटीन की ज़रूरत होती है। WHO और NHM पूरी गर्भावस्था और प्रसव के 6 महीने बाद तक रोज़ आयरन-फॉलिक एसिड (IFA) गोली की सलाह देते हैं। हरी पत्तेदार सब्ज़ियां, दाल, गुड़, अंडे और बाजरा खाएं। खूब पानी पिएं। कच्चा या अधपका मांस न खाएं। बहुत थकान, चक्कर, या नाखून/पलकों के अंदर पीलापन दिखे तो स्वास्थ्य कर्मी को बताएं — ये एनीमिया के संकेत हो सकते हैं।",
      kn: "ಗರ್ಭಧಾರಣೆಯಲ್ಲಿ ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚು ಕಬ್ಬಿಣ, ಫೋಲಿಕ್ ಆಮ್ಲ, ಕ್ಯಾಲ್ಸಿಯಂ ಮತ್ತು ಪ್ರೋಟೀನ್ ಅಗತ್ಯ. WHO ಮತ್ತು NHM ಇಡೀ ಗರ್ಭಧಾರಣೆ ಮತ್ತು ಹೆರಿಗೆಯ 6 ತಿಂಗಳ ನಂತರವೂ ದಿನನಿತ್ಯ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ (IFA) ಮಾತ್ರೆ ಶಿಫಾರಸು ಮಾಡುತ್ತಾರೆ. ಕಡು ಹಸಿರು ಸೊಪ್ಪುಗಳು, ಬೇಳೆ, ಬೆಲ್ಲ, ಮೊಟ್ಟೆ ಮತ್ತು ರಾಗಿ ತಿನ್ನಿ. ಸಾಕಷ್ಟು ನೀರು ಕುಡಿಯಿರಿ."
    },
  },

  // ═══════════════ MENSTRUAL ═══════════════
  {
    id: "men-normal-cycle",
    category: "menstrual",
    tags: ["period", "cycle", "normal", "irregular", "adolescent"],
    source: "WHO Adolescent Health Guidelines; FOGSI (Federation of Obstetric and Gynaecological Societies of India) Patient Education",
    title: { en: "What is a normal period?", hi: "सामान्य मासिक धर्म क्या है?", kn: "ಸಾಮಾನ್ಯ ಮುಟ್ಟು ಎಂದರೇನು?" },
    content: {
      en: "A typical menstrual cycle lasts between 21 and 35 days, counted from the first day of one period to the first day of the next. Bleeding usually lasts 3–7 days. Cycles may be irregular during the first 2–3 years after periods begin — this is normal. However, if periods are consistently less than 21 days apart or more than 45 days apart, if bleeding lasts more than 7 days, or if you soak through a pad/cloth in under an hour, talk to a health worker. Period pain (cramping in the lower abdomen) is common and usually manageable, but pain severe enough to stop daily activities every month needs evaluation.",
      hi: "सामान्य मासिक चक्र 21 से 35 दिन का होता है — एक मासिक धर्म के पहले दिन से अगले के पहले दिन तक। रक्तस्राव आमतौर पर 3–7 दिन रहता है। शुरुआत के 2–3 साल तक अनियमित चक्र सामान्य है। लेकिन अगर चक्र लगातार 21 दिन से कम या 45 दिन से ज़्यादा हो, रक्तस्राव 7 दिन से ज़्यादा हो, या एक घंटे में पैड भीग जाए, तो स्वास्थ्य कर्मी से बात करें। मासिक दर्द आम है, लेकिन अगर हर महीने दर्द इतना तेज़ हो कि रोज़मर्रा का काम रुक जाए तो जांच करवाएं।",
      kn: "ಸಾಮಾನ್ಯ ಋತುಚಕ್ರ 21 ರಿಂದ 35 ದಿನಗಳವರೆಗೆ ಇರುತ್ತದೆ — ಒಂದು ಮುಟ್ಟಿನ ಮೊದಲ ದಿನದಿಂದ ಮುಂದಿನ ಮುಟ್ಟಿನ ಮೊದಲ ದಿನದವರೆಗೆ. ರಕ್ತಸ್ರಾವ ಸಾಮಾನ್ಯವಾಗಿ 3–7 ದಿನ ಇರುತ್ತದೆ. ಮುಟ್ಟು ಶುರುವಾದ ಮೊದಲ 2–3 ವರ್ಷ ಅನಿಯಮಿತವಾಗಿರುವುದು ಸಾಮಾನ್ಯ. ಆದರೆ ಚಕ್ರ 21 ದಿನಕ್ಕಿಂತ ಕಡಿಮೆ ಅಥವಾ 45 ದಿನಕ್ಕಿಂತ ಹೆಚ್ಚು, ರಕ್ತಸ್ರಾವ 7 ದಿನ ಮೀರಿದರೆ, ಅಥವಾ ಒಂದು ಗಂಟೆಯಲ್ಲಿ ಪ್ಯಾಡ್ ತೊಯ್ಯಿದರೆ ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರ ಬಳಿ ಮಾತನಾಡಿ."
    },
  },
  {
    id: "men-hygiene",
    category: "menstrual",
    tags: ["period", "hygiene", "pad", "cloth", "infection"],
    source: "WHO/UNICEF Joint Monitoring Programme for Water Supply, Sanitation and Hygiene; NHM Menstrual Hygiene Scheme",
    title: { en: "Menstrual hygiene practices", hi: "मासिक स्वच्छता", kn: "ಮುಟ್ಟಿನ ನೈರ್ಮಲ್ಯ" },
    content: {
      en: "Change your pad or cloth at least every 4–6 hours, even on light days, to prevent infection. If using cloth, wash with soap and clean water and dry it in direct sunlight — damp cloth can cause fungal infections. Wash your hands before and after changing. India's NHM provides subsidised sanitary pads through the Menstrual Hygiene Scheme at many sub-centres — ask your ASHA worker. Itching, unusual discharge with a strong smell, or burning while urinating around your period are not normal — these may be signs of infection and should be checked.",
      hi: "संक्रमण रोकने के लिए पैड या कपड़ा हर 4–6 घंटे में बदलें, कम रक्तस्राव के दिन भी। कपड़ा इस्तेमाल करें तो साबुन और साफ पानी से धोकर सीधी धूप में सुखाएं — गीला कपड़ा फंगल संक्रमण का कारण बन सकता है। बदलने से पहले और बाद में हाथ धोएं। NHM की मासिक स्वच्छता योजना के तहत कई उप-केंद्रों पर सस्ते पैड उपलब्ध हैं — आशा कार्यकर्ता से पूछें। खुजली, तेज़ गंध वाला डिस्चार्ज, या पेशाब में जलन सामान्य नहीं है — ये संक्रमण के संकेत हो सकते हैं।",
      kn: "ಸೋಂಕು ತಡೆಯಲು ಪ್ಯಾಡ್ ಅಥವಾ ಬಟ್ಟೆಯನ್ನು ಕನಿಷ್ಠ 4–6 ಗಂಟೆಗಳಿಗೊಮ್ಮೆ ಬದಲಿಸಿ, ಕಡಿಮೆ ರಕ್ತಸ್ರಾವ ದಿನಗಳಲ್ಲೂ. ಬಟ್ಟೆ ಬಳಸಿದರೆ ಸಾಬೂನು ಮತ್ತು ಶುದ್ಧ ನೀರಿನಿಂದ ತೊಳೆದು ನೇರ ಬಿಸಿಲಿನಲ್ಲಿ ಒಣಗಿಸಿ — ಒದ್ದೆ ಬಟ್ಟೆ ಶಿಲೀಂಧ್ರ ಸೋಂಕಿಗೆ ಕಾರಣವಾಗಬಹುದು. NHM ಮುಟ್ಟಿನ ನೈರ್ಮಲ್ಯ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಅನೇಕ ಉಪ-ಕೇಂದ್ರಗಳಲ್ಲಿ ರಿಯಾಯಿತಿ ಪ್ಯಾಡ್‌ಗಳು ಲಭ್ಯ — ನಿಮ್ಮ ಆಶಾ ಕಾರ್ಯಕರ್ತರನ್ನು ಕೇಳಿ."
    },
  },

  // ═══════════════ ANAEMIA ═══════════════
  {
    id: "anm-what-is",
    category: "anaemia",
    tags: ["anaemia", "iron", "fatigue", "pale", "dizziness", "blood"],
    source: "WHO Global Anaemia Estimates (2021); NHM Anaemia Mukt Bharat Programme",
    title: { en: "What is anaemia and why it matters", hi: "एनीमिया क्या है और यह क्यों मायने रखता है", kn: "ರಕ್ತಹೀನತೆ ಎಂದರೇನು ಮತ್ತು ಅದು ಏಕೆ ಮುಖ್ಯ" },
    content: {
      en: "Anaemia means your blood has fewer healthy red blood cells than needed to carry enough oxygen around your body. In India, over 50% of women of reproductive age are anaemic (NHM data). Common signs include constant tiredness even after rest, dizziness, pale skin and inner eyelids, breathlessness on mild exertion, and cold hands/feet. Anaemia during pregnancy increases the risk of premature birth, low birth weight, and maternal death. It is confirmed by a simple blood test (haemoglobin level) — no screen or app can replace this test. Treatment usually involves iron-folic acid supplements and iron-rich foods. If anaemia is severe (Hb below 7 g/dL), a blood transfusion may be needed.",
      hi: "एनीमिया का मतलब है कि आपके खून में शरीर को पर्याप्त ऑक्सीजन पहुंचाने के लिए पर्याप्त स्वस्थ लाल रक्त कोशिकाएं नहीं हैं। भारत में प्रजनन आयु की 50% से अधिक महिलाएं एनीमिक हैं (NHM)। लक्षण: आराम के बाद भी थकान, चक्कर, त्वचा और पलकों के अंदर पीलापन, हल्के काम में सांस फूलना। गर्भावस्था में एनीमिया समय पूर्व जन्म, कम वज़न और मातृ मृत्यु का खतरा बढ़ाता है। पुष्टि सिर्फ रक्त जांच (हीमोग्लोबिन) से होती है — कोई स्क्रीन या ऐप इसकी जगह नहीं ले सकता।",
      kn: "ರಕ್ತಹೀನತೆ ಎಂದರೆ ನಿಮ್ಮ ದೇಹಕ್ಕೆ ಸಾಕಷ್ಟು ಆಮ್ಲಜನಕ ಒದಗಿಸಲು ಅಗತ್ಯವಾದ ಆರೋಗ್ಯಕರ ಕೆಂಪು ರಕ್ತ ಕಣಗಳು ಕಡಿಮೆಯಾಗಿವೆ. ಭಾರತದಲ್ಲಿ ಸಂತಾನೋತ್ಪತ್ತಿ ವಯಸ್ಸಿನ 50%ಕ್ಕಿಂತ ಹೆಚ್ಚು ಮಹಿಳೆಯರು ರಕ್ತಹೀನತೆ ಹೊಂದಿದ್ದಾರೆ (NHM). ಲಕ್ಷಣಗಳು: ವಿಶ್ರಾಂತಿಯ ನಂತರವೂ ನಿರಂತರ ಆಯಾಸ, ತಲೆ ಸುತ್ತುವಿಕೆ, ಚರ್ಮ ಮತ್ತು ಕಣ್ಣುಗಳ ಒಳಭಾಗ ಬಿಳಿಯಾಗುವುದು. ಖಚಿತಪಡಿಸಲು ಸರಳ ರಕ್ತ ಪರೀಕ್ಷೆ (ಹಿಮೋಗ್ಲೋಬಿನ್ ಮಟ್ಟ) ಬೇಕು — ಯಾವುದೇ ಸ್ಕ್ರೀನ್ ಅಥವಾ ಆ್ಯಪ್ ಈ ಪರೀಕ್ಷೆಯ ಬದಲಿಯಾಗಲಾರದು."
    },
  },
  {
    id: "anm-iron-foods",
    category: "anaemia",
    tags: ["anaemia", "iron", "nutrition", "diet", "food"],
    source: "WHO Iron Supplementation Guidelines; ICMR Dietary Guidelines for Indians (2024)",
    title: { en: "Iron-rich foods available in rural India", hi: "ग्रामीण भारत में उपलब्ध आयरन-युक्त भोजन", kn: "ಗ್ರಾಮೀಣ ಭಾರತದಲ್ಲಿ ಲಭ್ಯವಿರುವ ಕಬ್ಬಿಣಾಂಶ ಭರಿತ ಆಹಾರ" },
    content: {
      en: "Iron-rich foods that are widely available and affordable: dark green leafy vegetables (spinach, amaranth, drumstick leaves, fenugreek), lentils and all varieties of dal, ragi/finger millet, jaggery, sesame seeds, groundnuts, eggs, and small dried fish. Eating these with a source of vitamin C (lemon juice, amla, tomato, guava) helps your body absorb more iron. Tea and coffee drunk with meals reduce iron absorption — try to have them between meals instead. These foods support iron-folic acid supplements but do not replace them during pregnancy — continue your IFA tablets as prescribed.",
      hi: "आयरन-युक्त, सस्ते और आसानी से उपलब्ध खाद्य पदार्थ: गहरी हरी पत्तेदार सब्ज़ियां (पालक, चौलाई, सहजन पत्ती, मेथी), सभी प्रकार की दालें, रागी, गुड़, तिल, मूंगफली, अंडे और छोटी सूखी मछली। इन्हें विटामिन C (नींबू, आंवला, टमाटर, अमरूद) के साथ खाने से शरीर अधिक आयरन सोखता है। खाने के साथ चाय-कॉफी आयरन का अवशोषण कम करती है — भोजन के बीच में पिएं। ये खाद्य पदार्थ IFA गोली का सहयोग करते हैं, गर्भावस्था में उनकी जगह नहीं लेते।",
      kn: "ಕಬ್ಬಿಣಾಂಶ ಭರಿತ, ಕೈಗೆಟುಕುವ ಆಹಾರಗಳು: ಕಡು ಹಸಿರು ಸೊಪ್ಪುಗಳು (ಪಾಲಕ್, ರಾಜಗಿರಿ, ನುಗ್ಗೆ ಎಲೆ, ಮೆಂತ್ಯ), ಎಲ್ಲ ಬೇಳೆಕಾಳುಗಳು, ರಾಗಿ, ಬೆಲ್ಲ, ಎಳ್ಳು, ಕಡಲೆಕಾಯಿ, ಮೊಟ್ಟೆ ಮತ್ತು ಸಣ್ಣ ಒಣ ಮೀನು. ಇವನ್ನು ವಿಟಮಿನ್ C ಜೊತೆ (ನಿಂಬೆ ರಸ, ಆಮ್ಲ, ಟೊಮೇಟೊ) ತಿನ್ನುವುದರಿಂದ ಕಬ್ಬಿಣಾಂಶ ಹೆಚ್ಚು ಹೀರಲ್ಪಡುತ್ತದೆ."
    },
  },

  // ═══════════════ ADOLESCENT ═══════════════
  {
    id: "ado-puberty",
    category: "adolescent",
    tags: ["puberty", "adolescent", "body", "changes", "normal"],
    source: "WHO Adolescent Health Guidelines; RKSK (Rashtriya Kishor Swasthya Karyakram) Training Module",
    title: { en: "Body changes during puberty", hi: "यौवन में शरीर के बदलाव", kn: "ಯೌವನದಲ್ಲಿ ದೇಹದ ಬದಲಾವಣೆಗಳು" },
    content: {
      en: "Puberty usually begins between ages 8 and 13 for girls, and 10 and 15 for boys. For girls, early changes include breast development, body hair, a growth spurt, skin changes, and eventually the start of periods. These are normal and healthy. Everyone's timing is different — starting earlier or later than friends does not mean something is wrong. If no signs of puberty have appeared by age 14, or if periods have not started by age 16, a health check-up is recommended. Under India's RKSK programme, adolescents can access free health services at Adolescent Friendly Health Clinics (AFHCs) at district hospitals and CHCs.",
      hi: "लड़कियों में यौवन आमतौर पर 8–13 साल और लड़कों में 10–15 साल में शुरू होता है। लड़कियों में शुरुआती बदलाव: स्तन विकास, शरीर पर बाल, तेज़ वृद्धि, त्वचा में बदलाव और मासिक धर्म की शुरुआत। ये सामान्य हैं। सबका समय अलग होता है — दोस्तों से पहले या बाद में शुरू होना ग़लत नहीं है। 14 साल तक कोई संकेत न दिखे या 16 साल तक मासिक धर्म शुरू न हो तो जांच करवाएं। RKSK कार्यक्रम के तहत किशोर-अनुकूल स्वास्थ्य क्लीनिक (AFHC) में मुफ्त सेवाएं उपलब्ध हैं।",
      kn: "ಹುಡುಗಿಯರಲ್ಲಿ ಯೌವನ ಸಾಮಾನ್ಯವಾಗಿ 8–13 ವರ್ಷ ಮತ್ತು ಹುಡುಗರಲ್ಲಿ 10–15 ವರ್ಷದಲ್ಲಿ ಆರಂಭವಾಗುತ್ತದೆ. ಹುಡುಗಿಯರಲ್ಲಿ ಆರಂಭಿಕ ಬದಲಾವಣೆಗಳು: ಸ್ತನ ಬೆಳವಣಿಗೆ, ದೇಹದ ಕೂದಲು, ಬೆಳವಣಿಗೆ, ಚರ್ಮ ಬದಲಾವಣೆ ಮತ್ತು ಮುಟ್ಟಿನ ಆರಂಭ. ಇವು ಸಾಮಾನ್ಯ. 14 ವರ್ಷದವರೆಗೂ ಯಾವುದೇ ಸೂಚನೆ ಕಾಣದಿದ್ದರೆ ಅಥವಾ 16 ವರ್ಷದವರೆಗೂ ಮುಟ್ಟು ಆರಂಭವಾಗದಿದ್ದರೆ ತಪಾಸಣೆ ಮಾಡಿಸಿ."
    },
  },

  // ═══════════════ INFECTION ═══════════════
  {
    id: "inf-fever-when",
    category: "infection",
    tags: ["fever", "infection", "malaria", "dengue", "typhoid"],
    source: "WHO Integrated Management of Childhood Illness (IMCI) Guidelines; NHM NVBDCP (National Vector Borne Disease Control Programme)",
    title: { en: "Fever: when to worry", hi: "बुखार: कब चिंता करें", kn: "ಜ್ವರ: ಯಾವಾಗ ಕಾಳಜಿ ಮಾಡಬೇಕು" },
    content: {
      en: "Most fevers are the body fighting an infection and resolve in 2–3 days with rest and fluids. However, seek care immediately if: fever is very high (above 103°F / 39.4°C), fever lasts more than 3 days, it comes with a severe headache and stiff neck, there is a rash that does not blanch when pressed, there is difficulty breathing, the person is confused or unusually drowsy, or there is blood in vomit/stool. In rural India, fever lasting more than 3 days with chills could suggest malaria, dengue, or typhoid — all treatable but dangerous if delayed. Your sub-centre or PHC can do rapid diagnostic tests for malaria and dengue at no cost under the NVBDCP.",
      hi: "अधिकांश बुखार शरीर का संक्रमण से लड़ना है और 2–3 दिन में आराम और तरल पदार्थों से ठीक हो जाता है। लेकिन तुरंत देखभाल लें अगर: बुखार बहुत तेज़ (103°F / 39.4°C से ऊपर), 3 दिन से ज़्यादा हो, तेज़ सिरदर्द और गर्दन अकड़न के साथ हो, दबाने पर न मिटने वाला रैश हो, सांस लेने में तकलीफ हो, भ्रम या असामान्य उनींदापन हो। ग्रामीण भारत में 3 दिन से ज़्यादा बुखार ठंड के साथ मलेरिया, डेंगू या टाइफाइड हो सकता है — उप-केंद्र या PHC में NVBDCP के तहत मुफ्त जांच उपलब्ध है।",
      kn: "ಹೆಚ್ಚಿನ ಜ್ವರ ಸೋಂಕಿನ ವಿರುದ್ಧ ದೇಹ ಹೋರಾಡುತ್ತಿರುವ ಸೂಚನೆಯಾಗಿದ್ದು 2–3 ದಿನಗಳಲ್ಲಿ ವಿಶ್ರಾಂತಿ ಮತ್ತು ದ್ರವಗಳಿಂದ ಗುಣವಾಗುತ್ತದೆ. ಆದರೆ ತಕ್ಷಣ ಆರೈಕೆ ಪಡೆಯಿರಿ: ಜ್ವರ ತೀವ್ರವಾಗಿದ್ದರೆ (103°F ಮೇಲೆ), 3 ದಿನ ಮೀರಿದರೆ, ತೀವ್ರ ತಲೆನೋವು ಮತ್ತು ಕುತ್ತಿಗೆ ಬಿಗಿತದೊಂದಿಗೆ ಬಂದರೆ, ಒತ್ತಿದಾಗ ಮಾಸದ ರ‍್ಯಾಶ್ ಇದ್ದರೆ. ಗ್ರಾಮೀಣ ಭಾರತದಲ್ಲಿ 3 ದಿನ ಮೀರಿದ ಶೀತ ಜ್ವರ ಮಲೇರಿಯಾ, ಡೆಂಗ್ಯೂ ಅಥವಾ ಟೈಫಾಯ್ಡ್ ಆಗಿರಬಹುದು — NVBDCP ಅಡಿಯಲ್ಲಿ ಉಪ-ಕೇಂದ್ರದಲ್ಲಿ ಉಚಿತ ತ್ವರಿತ ಪರೀಕ್ಷೆ ಲಭ್ಯ."
    },
  },
  {
    id: "inf-uti",
    category: "infection",
    tags: ["urinary", "uti", "burning", "infection"],
    source: "WHO Model List of Essential Medicines; FOGSI Guidelines on UTI in Women",
    title: { en: "Urinary tract infections (UTIs)", hi: "मूत्र मार्ग संक्रमण (UTI)", kn: "ಮೂತ್ರನಾಳದ ಸೋಂಕು (UTI)" },
    content: {
      en: "A UTI causes burning or pain while urinating, needing to urinate more often, cloudy or strong-smelling urine, and sometimes lower abdominal pain. UTIs are more common in women and during pregnancy. Drink plenty of water and do not delay urination. UTIs are treated with a short course of antibiotics prescribed by a health worker — do not self-medicate. If a UTI comes with fever, back pain, or blood in urine, it may have reached the kidneys and needs prompt treatment. During pregnancy, even a UTI without symptoms can be harmful and is checked during antenatal visits.",
      hi: "UTI से पेशाब में जलन या दर्द, बार-बार पेशाब जाना, गंदा या तेज़ गंध वाला पेशाब और कभी-कभी पेट के निचले हिस्से में दर्द होता है। महिलाओं और गर्भावस्था में UTI ज़्यादा आम है। खूब पानी पिएं और पेशाब रोकें नहीं। UTI का इलाज स्वास्थ्य कर्मी द्वारा दी गई एंटीबायोटिक से होता है — खुद दवा न लें। बुखार, कमर दर्द या पेशाब में खून के साथ UTI हो तो यह गुर्दों तक पहुंच गई हो सकती है — तुरंत इलाज ज़रूरी है।",
      kn: "UTI ಯಿಂದ ಮೂತ್ರ ವಿಸರ್ಜನೆಯಲ್ಲಿ ಉರಿ ಅಥವಾ ನೋವು, ಪದೇ ಪದೇ ಮೂತ್ರ ವಿಸರ್ಜನೆ, ಮಸುಕಾದ ಅಥವಾ ತೀವ್ರ ವಾಸನೆಯ ಮೂತ್ರ ಮತ್ತು ಕೆಲವೊಮ್ಮೆ ಹೊಟ್ಟೆಯ ಕೆಳಭಾಗದ ನೋವು ಉಂಟಾಗುತ್ತದೆ. ಮಹಿಳೆಯರಲ್ಲಿ ಮತ್ತು ಗರ್ಭಧಾರಣೆಯಲ್ಲಿ UTI ಹೆಚ್ಚು ಸಾಮಾನ್ಯ. ಸಾಕಷ್ಟು ನೀರು ಕುಡಿಯಿರಿ ಮತ್ತು ಮೂತ್ರ ವಿಸರ್ಜನೆ ತಡೆಹಿಡಿಯಬೇಡಿ."
    },
  },

  // ═══════════════ EMERGENCY ═══════════════
  {
    id: "emer-general",
    category: "emergency",
    tags: ["emergency", "hospital", "call", "108", "112"],
    source: "WHO Emergency Triage Assessment and Treatment (ETAT); NHM 108 Emergency Response Service Guidelines",
    title: { en: "When to go to hospital immediately", hi: "तुरंत अस्पताल कब जाएं", kn: "ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಯಾವಾಗ ಹೋಗಬೇಕು" },
    content: {
      en: "Call 108 (ambulance) or 112 (emergency) and go to the nearest hospital immediately for any of these: chest pain or pressure, difficulty breathing or inability to speak in full sentences, unconsciousness or unresponsiveness, heavy uncontrolled bleeding from any cause, convulsions/seizures, sudden severe headache with vision changes, suspected poisoning, severe burn, severe allergic reaction (swelling of face/throat, difficulty swallowing). While waiting for help: keep the person lying down if unconscious (on their side, not their back), apply firm pressure to any bleeding wound with a clean cloth, do not give food or water to an unconscious person.",
      hi: "इनमें से कोई भी हो तो 108 (एम्बुलेंस) या 112 (आपातकालीन) पर कॉल करें और तुरंत अस्पताल जाएं: सीने में दर्द, सांस लेने में तकलीफ, बेहोशी, किसी भी कारण से बेकाबू रक्तस्राव, दौरे, अचानक तेज़ सिरदर्द, ज़हर खाने का शक, गंभीर जलन, गंभीर एलर्जी। मदद आने तक: बेहोश व्यक्ति को करवट पर लिटाएं, खून बह रहे घाव पर साफ कपड़े से दबाव रखें, बेहोश व्यक्ति को खाना-पानी न दें।",
      kn: "ಇವುಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ಇದ್ದರೆ 108 (ಆಂಬ್ಯುಲೆನ್ಸ್) ಅಥವಾ 112 (ತುರ್ತು) ಗೆ ಕರೆ ಮಾಡಿ ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಹೋಗಿ: ಎದೆ ನೋವು, ಉಸಿರಾಟದ ತೊಂದರೆ, ಮೂರ್ಛೆ, ಅನಿಯಂತ್ರಿತ ರಕ್ತಸ್ರಾವ, ಸೆಳೆತ, ಇದ್ದಕ್ಕಿದ್ದಂತೆ ತೀವ್ರ ತಲೆನೋವು, ವಿಷ ಸೇವನೆ ಶಂಕೆ, ತೀವ್ರ ಸುಟ್ಟಗಾಯ, ತೀವ್ರ ಅಲರ್ಜಿ. ಸಹಾಯ ಬರುವವರೆಗೆ: ಮೂರ್ಛೆ ಹೋದ ವ್ಯಕ್ತಿಯನ್ನು ಪಕ್ಕಕ್ಕೆ ಮಲಗಿಸಿ, ರಕ್ತಸ್ರಾವದ ಗಾಯಕ್ಕೆ ಶುಭ್ರ ಬಟ್ಟೆಯಿಂದ ಒತ್ತಡ ಹಾಕಿ."
    },
  },

  // ═══════════════ HYGIENE ═══════════════
  {
    id: "hyg-handwash",
    category: "hygiene",
    tags: ["handwashing", "hygiene", "prevention", "diarrhoea"],
    source: "WHO Guidelines on Hand Hygiene; NHM Swachh Bharat Swasth Bharat",
    title: { en: "Handwashing: when and how", hi: "हाथ धोना: कब और कैसे", kn: "ಕೈ ತೊಳೆಯುವಿಕೆ: ಯಾವಾಗ ಮತ್ತು ಹೇಗೆ" },
    content: {
      en: "Washing hands with soap and water for at least 20 seconds is the single most effective way to prevent diarrhoea, pneumonia, and many infections. Always wash: before eating or preparing food, after using the toilet, after changing a baby's nappy, after coughing/sneezing, after touching an animal. If soap and water aren't available, an alcohol-based sanitiser (at least 60% alcohol) can be used, but it does not remove all types of germs and is not effective when hands are visibly dirty. The WHO estimates that handwashing with soap could reduce diarrhoeal deaths by almost 50%.",
      hi: "साबुन और पानी से कम से कम 20 सेकंड हाथ धोना दस्त, निमोनिया और कई संक्रमणों को रोकने का सबसे प्रभावी तरीका है। हमेशा धोएं: खाना खाने या बनाने से पहले, शौचालय के बाद, बच्चे का नैपी बदलने के बाद, खांसने/छींकने के बाद। WHO अनुमान है कि साबुन से हाथ धोने से दस्त से होने वाली मौतें लगभग 50% कम हो सकती हैं।",
      kn: "ಸಾಬೂನು ಮತ್ತು ನೀರಿನಿಂದ ಕನಿಷ್ಠ 20 ಸೆಕೆಂಡು ಕೈ ತೊಳೆಯುವುದು ಅತಿಸಾರ, ನ್ಯೂಮೋನಿಯಾ ಮತ್ತು ಅನೇಕ ಸೋಂಕುಗಳನ್ನು ತಡೆಯುವ ಅತ್ಯಂತ ಪರಿಣಾಮಕಾರಿ ಮಾರ್ಗ. ಯಾವಾಗಲೂ ತೊಳೆಯಿರಿ: ಊಟಕ್ಕೆ ಮೊದಲು, ಶೌಚಾಲಯದ ನಂತರ, ಮಗುವಿನ ಡೈಪರ್ ಬದಲಿಸಿದ ನಂತರ. ಸಾಬೂನಿನಿಂದ ಕೈ ತೊಳೆಯುವುದರಿಂದ ಅತಿಸಾರ ಮರಣ ಸುಮಾರು 50% ಕಡಿಮೆಯಾಗಬಹುದು ಎಂದು WHO ಅಂದಾಜಿಸಿದೆ."
    },
  },
  {
    id: "hyg-safe-water",
    category: "hygiene",
    tags: ["water", "safe", "drinking", "diarrhoea", "ORS"],
    source: "WHO Guidelines on Drinking-water Quality; NHM Jal Jeevan Mission Health Component",
    title: { en: "Safe drinking water and ORS", hi: "सुरक्षित पेयजल और ORS", kn: "ಸುರಕ್ಷಿತ ಕುಡಿಯುವ ನೀರು ಮತ್ತು ORS" },
    content: {
      en: "Unsafe water is a leading cause of diarrhoea, which kills more children under 5 in India than almost any other cause. If you are not sure your water is clean: boil it for at least 1 minute and let it cool before drinking, or use chlorine tablets if available from your ASHA worker or sub-centre. If someone has diarrhoea: start oral rehydration solution (ORS) immediately — mix one ORS packet in 1 litre of clean water and sip frequently. If ORS packets are not available, mix 6 level teaspoons of sugar and half a level teaspoon of salt in 1 litre of clean water. Seek medical help if diarrhoea lasts more than 2 days, if there is blood in the stool, or if the person shows signs of dehydration (very little urine, sunken eyes, dry mouth).",
      hi: "असुरक्षित पानी दस्त का प्रमुख कारण है। अगर पानी साफ होने की पुष्टि नहीं है: कम से कम 1 मिनट उबालें और ठंडा होने दें, या आशा कार्यकर्ता से क्लोरीन टैबलेट लें। दस्त होने पर: तुरंत ORS शुरू करें — एक पैकेट 1 लीटर साफ पानी में मिलाकर बार-बार पिएं। पैकेट न हो तो 6 चम्मच चीनी और आधा चम्मच नमक 1 लीटर पानी में मिलाएं। 2 दिन से ज़्यादा दस्त, खून आना, या निर्जलीकरण (बहुत कम पेशाब, धंसी आंखें) होने पर चिकित्सा सहायता लें।",
      kn: "ಅಸುರಕ್ಷಿತ ನೀರು ಅತಿಸಾರದ ಪ್ರಮುಖ ಕಾರಣ. ನೀರು ಶುದ್ಧ ಎಂದು ಖಚಿತವಿಲ್ಲದಿದ್ದರೆ: ಕನಿಷ್ಠ 1 ನಿಮಿಷ ಕುದಿಸಿ ತಣ್ಣಗಾಗಲು ಬಿಡಿ. ಅತಿಸಾರ ಇದ್ದರೆ: ತಕ್ಷಣ ORS ಪ್ರಾರಂಭಿಸಿ — ಒಂದು ORS ಪ್ಯಾಕೆಟ್ 1 ಲೀಟರ್ ಶುದ್ಧ ನೀರಿನಲ್ಲಿ ಬೆರೆಸಿ ಪದೇ ಪದೇ ಕುಡಿಯಿರಿ. ORS ಇಲ್ಲದಿದ್ದರೆ 6 ಚಮಚ ಸಕ್ಕರೆ ಮತ್ತು ಅರ್ಧ ಚಮಚ ಉಪ್ಪು 1 ಲೀಟರ್ ನೀರಿನಲ್ಲಿ ಬೆರೆಸಿ."
    },
  },

  // ═══════════════ MENTAL ═══════════════
  {
    id: "mnt-stress",
    category: "mental",
    tags: ["mental", "stress", "anxiety", "sleep", "wellbeing"],
    source: "WHO Mental Health Gap Action Programme (mhGAP); NHM National Mental Health Programme (NMHP)",
    title: { en: "Stress and anxiety: what helps", hi: "तनाव और चिंता: क्या मदद करता है", kn: "ಒತ್ತಡ ಮತ್ತು ಆತಂಕ: ಏನು ಸಹಾಯ ಮಾಡುತ್ತದೆ" },
    content: {
      en: "Feeling worried, tense, or unable to sleep from time to time is normal, especially during illness, pregnancy, or difficult life situations. It becomes a health concern when it stops you from doing daily activities, lasts for weeks, or feels uncontrollable. Steps that help: talking to someone you trust (a family member, friend, or health worker), maintaining a daily routine including regular meals and sleep, staying physically active, and reducing tea/coffee near bedtime. India's National Mental Health Programme provides free mental health services at district hospitals — ask for a referral if needed. If someone talks about wanting to end their life or hurt themselves, this is a medical emergency — stay with them and get help immediately.",
      hi: "कभी-कभी चिंता, तनाव या नींद न आना सामान्य है, खासकर बीमारी, गर्भावस्था या कठिन परिस्थितियों में। यह चिंता का विषय तब बनता है जब यह रोज़मर्रा के काम में बाधा डाले, हफ्तों तक रहे, या बेकाबू लगे। मदद करता है: किसी भरोसेमंद व्यक्ति से बात करना, नियमित दिनचर्या, शारीरिक गतिविधि, सोने से पहले चाय-कॉफी कम करना। राष्ट्रीय मानसिक स्वास्थ्य कार्यक्रम के तहत ज़िला अस्पतालों में मुफ्त सेवाएं उपलब्ध हैं। यदि कोई खुद को नुकसान पहुंचाने या जीवन समाप्त करने की बात करे — यह आपातकाल है, उनके साथ रहें और तुरंत मदद लें।",
      kn: "ಆಗಾಗ ಚಿಂತೆ, ಒತ್ತಡ ಅಥವಾ ನಿದ್ದೆ ಬಾರದಿರುವುದು ಸಾಮಾನ್ಯ, ವಿಶೇಷವಾಗಿ ಅನಾರೋಗ್ಯ, ಗರ್ಭಧಾರಣೆ ಅಥವಾ ಕಷ್ಟದ ಸಮಯದಲ್ಲಿ. ಇದು ದೈನಂದಿನ ಕೆಲಸಕ್ಕೆ ಅಡ್ಡಿಯಾದಾಗ, ವಾರಗಟ್ಟಲೆ ಮುಂದುವರಿದಾಗ ಅಥವಾ ನಿಯಂತ್ರಿಸಲಾಗದಂತೆ ಅನಿಸಿದಾಗ ಆರೋಗ್ಯ ಸಮಸ್ಯೆ. ಸಹಾಯ ಮಾಡುವುದು: ನಂಬಿಕೆಯ ವ್ಯಕ್ತಿಯೊಂದಿಗೆ ಮಾತನಾಡುವುದು, ನಿಯಮಿತ ದಿನಚರಿ, ದೈಹಿಕ ಚಟುವಟಿಕೆ. ಯಾರಾದರೂ ತಮ್ಮ ಜೀವನ ಕೊನೆಗೊಳಿಸಲು ಅಥವಾ ತಮಗೆ ತಾವೇ ಹಾನಿ ಮಾಡಿಕೊಳ್ಳಲು ಮಾತನಾಡಿದರೆ — ಇದು ವೈದ್ಯಕೀಯ ತುರ್ತುಸ್ಥಿತಿ, ಅವರ ಜೊತೆ ಇರಿ ಮತ್ತು ತಕ್ಷಣ ಸಹಾಯ ಪಡೆಯಿರಿ."
    },
  },
];
