-- 001_schema.sql
-- Durable storage for triage sessions.
--
-- Run this once in the Supabase SQL editor (or via `supabase db push`).
--
-- SCOPE NOTE: this migration creates the session table only. ASHA worker
-- accounts and the audit trail deliberately stay where they are, in
-- security/accounts.js and security/audit.js, because workers authenticate
-- against this server rather than Supabase Auth. There is therefore no
-- auth.users to reference and no auth.uid() for RLS to key off. If auth ever
-- moves to Supabase, asha_workers and audit_log come with it in 002.

CREATE TABLE IF NOT EXISTS triage_sessions (
  id          TEXT PRIMARY KEY,             -- nanoid, generated by the server
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  language    TEXT NOT NULL DEFAULT 'en',
  intake      JSONB NOT NULL,
  triage      JSONB NOT NULL,
  routing     JSONB NOT NULL,
  self_care   JSONB
  -- No name, no phone, no address, no patient identifier of any kind. A girl
  -- checking a symptom is anonymous by design, and the schema is where that
  -- promise has to be enforced — anything the table cannot hold cannot leak.
);

-- The dashboard queue reads newest-first and nothing else, so one index carries
-- the only query that runs at any volume.
CREATE INDEX IF NOT EXISTS triage_sessions_created_at_idx
  ON triage_sessions (created_at DESC);

-- The queue filters by urgency and by "does an ASHA need to be alerted", both
-- of which live inside JSONB. Without these the filter degrades to a full scan.
CREATE INDEX IF NOT EXISTS triage_sessions_level_idx
  ON triage_sessions ((triage ->> 'level'));

CREATE INDEX IF NOT EXISTS triage_sessions_asha_alert_idx
  ON triage_sessions ((routing ->> 'ashaAlert'));

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- RLS is enabled with NO policies attached. That is intentional and is the
-- strictest possible setting: it denies every request made with the anon or
-- authenticated key, which is exactly what should happen, because no browser
-- should ever talk to this table directly.
--
-- The server reaches these rows with the service-role key, which bypasses RLS.
-- Authorization for real callers happens one layer up, in requireAuth +
-- requireCsrf on /api/sessions, where a worker's session cookie is checked and
-- the access is written to the audit log. Adding a permissive policy here would
-- not add a check — it would only widen who can reach the data.
ALTER TABLE triage_sessions ENABLE ROW LEVEL SECURITY;

-- Belt and braces: the anon key is shipped to browsers, so revoke its table
-- privileges outright rather than relying on RLS alone.
REVOKE ALL ON triage_sessions FROM anon, authenticated;
