-- 002_patient_history.sql
-- Opt-in, login-gated health history for patient accounts.  (Point 2)
--
-- Run this once in the Supabase SQL editor, after 001_schema.sql.
--
-- ---------------------------------------------------------------------------
-- READ THIS BEFORE ENABLING
-- ---------------------------------------------------------------------------
-- This table intentionally does what security/patientAuth.js warned against:
-- it links health findings (triage level, anaemia screen, cycle notes) to a
-- patient login. It exists because the product now wants a logged-in user's
-- history to follow them between devices. That is a legitimate choice, but it
-- carries a real cost — a database that can be subpoenaed, leaked or
-- shoulder-read — and the following mitigations are part of the deal:
--
--   * It is OPT-IN. The client only writes here when the user turns history on.
--   * It is USER-DELETABLE. DELETE /api/user/history wipes an account's rows
--     (right to erasure), and deleting the account should cascade.
--   * It holds no name, phone or address — only the account id and the finding.
--   * Consider enabling Supabase encryption / pgsodium for `data` if this goes
--     to a real population. For a demo the RLS lockdown below is the floor.

CREATE TABLE IF NOT EXISTS patient_history (
  id          TEXT PRIMARY KEY,               -- nanoid, generated by the server
  account_id  TEXT NOT NULL,                  -- patient account id (patientAuth)
  kind        TEXT NOT NULL,                  -- 'triage' | 'anaemia' | 'cycle' | 'location' | 'report'
  data        JSONB NOT NULL,                 -- the finding itself
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The only query that runs at volume: one account's history, newest first.
CREATE INDEX IF NOT EXISTS patient_history_account_idx
  ON patient_history (account_id, created_at DESC);

-- Same posture as triage_sessions: RLS on with NO policies denies every anon/
-- authenticated request. The server reaches these rows only with the
-- service-role key, and authorization happens one layer up in requirePatientAuth
-- (the caller can only ever touch their OWN account_id).
ALTER TABLE patient_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON patient_history FROM anon, authenticated;
