-- 003_patient_accounts.sql
-- Patient accounts (username / password / recovery email) in Postgres.
--
-- Run this once in the Supabase SQL editor, after 001 and 002.
--
-- Until now these lived in a local JSON file (fine for zero-config demos, but
-- lost on an ephemeral disk and not shared across instances). Moving them here
-- means EVERYTHING a user creates — triage sessions (001), health history (002),
-- and now their account (003) — is in one durable, backed-up Postgres database.
--
-- Still no health data on THIS table: an account row holds a handle, a password
-- HASH (never a plaintext password), an optional recovery email, and a language
-- preference. Health history is its own table (002), linked only by account id.

CREATE TABLE IF NOT EXISTS patient_accounts (
  id             TEXT PRIMARY KEY,               -- uuid, generated by the server
  handle         TEXT UNIQUE NOT NULL,           -- the username, lower-cased
  email          TEXT,                           -- recovery email (optional at DB level)
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  password_hash  TEXT NOT NULL,                  -- scrypt/argon hash — never plaintext
  language       TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at  TIMESTAMPTZ
);

-- One account per email (case-insensitive), but only among rows that HAVE an
-- email — several accounts may have none.
CREATE UNIQUE INDEX IF NOT EXISTS patient_accounts_email_idx
  ON patient_accounts (LOWER(email)) WHERE email IS NOT NULL;

-- Same lockdown as every other table here: RLS on, no policies, privileges
-- revoked from the browser-facing keys. Only the server's service-role key
-- reaches these rows; authorization happens in the app (patientAuth.js).
ALTER TABLE patient_accounts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON patient_accounts FROM anon, authenticated;
